import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{io}from"socket.io-client";import"./style.css";
const API=location.hostname==="localhost"?(localStorage.getItem("okeyServer")||"http://localhost:3001"):location.origin;
const s=io(API),COL={"Siyah":"#151515","Kırmızı":"#d52727","Mavi":"#176fd1","Sarı":"#d89b00"};
const AVATARS=["🦁","🐺","🦅","🐯","🦊","👑","🎩","🕶️","⚡","🔥","🌙","⭐"];
const savedProfile=(()=>{try{return JSON.parse(localStorage.getItem("okeyProfile")||"{}")}catch{return{}}})();
function Tile({t,sel,onClick,drag,onDrop,isOkey=false,allowReveal=false}){
 const[reveal,setReveal]=React.useState(false),timer=React.useRef(null),progress=React.useRef(null);
 const begin=e=>{if(!allowReveal||!isOkey)return;timer.current=setTimeout(()=>setReveal(true),5000)};
 const endHold=()=>{if(timer.current)clearTimeout(timer.current)};
 React.useEffect(()=>()=>timer.current&&clearTimeout(timer.current),[]);
 return <button draggable={!!drag} onDragStart={drag} onDragOver={e=>e.preventDefault()} onDrop={onDrop}
  onMouseDown={begin} onMouseUp={endHold} onMouseLeave={endHold} onTouchStart={begin} onTouchEnd={endHold}
  className={"tile "+(sel?"selected ":"")+(reveal?"revealed ":"")} onClick={onClick}>
  <span className="tileface front">{t.c==="Sahte"?<><b className="fake">★</b><small>SAHTE</small></>:<><b style={{color:COL[t.c]}}>{t.n}</b><i style={{background:COL[t.c]}}/></>}</span>
  <span className="tileface back"><b>★</b><small>OKEY</small></span>
 </button>
}

function logical(t,st){if(!t)return null;if(t.c==="Sahte"&&st?.indicator)return{...t,c:st.indicator.c,n:st.okey.n};return t}
function jokerTile(t,st){return !!(t&&st?.okey&&t.c===st.okey.c&&t.n===st.okey.n)}
function validGroup(ts,st){
 if(ts.length<3)return false;let js=ts.filter(t=>jokerTile(t,st)).length,a=ts.filter(t=>!jokerTile(t,st)).map(t=>logical(t,st));if(!a.length)return true;
 if(a.every(t=>t.n===a[0].n)&&new Set(a.map(t=>t.c)).size===a.length&&a.length+js<=4)return true;
 if(!a.every(t=>t.c===a[0].c))return false;let ns=a.map(t=>t.n).sort((x,y)=>x-y);if(new Set(ns).size!==ns.length)return false;let gaps=0;for(let i=1;i<ns.length;i++)gaps+=ns[i]-ns[i-1]-1;return gaps<=js
}
function rackGroups(slots,st){let out=[],cur=[];for(let t of slots){if(t)cur.push(t);else{if(cur.length){out.push(cur);cur=[]}}}if(cur.length)out.push(cur);return out.filter(g=>validGroup(g,st))}
function perValue(groups,st){return groups.flat().reduce((z,t)=>z+(jokerTile(t,st)?0:(logical(t,st)?.n||0)),0)}
function pairAnalysis(slots,st){let tiles=slots.filter(Boolean),used=new Set(),pairs=0;for(let i=0;i<tiles.length;i++)for(let j=i+1;j<tiles.length;j++){if(used.has(i)||used.has(j)||jokerTile(tiles[i],st)||jokerTile(tiles[j],st))continue;let a=logical(tiles[i],st),b=logical(tiles[j],st);if(a.c===b.c&&a.n===b.n){used.add(i);used.add(j);pairs++}}
 let jok=tiles.filter(t=>jokerTile(t,st)).length,need=Math.max(0,5-pairs),useJ=Math.min(jok,need),count=pairs+useJ,remaining=tiles.filter((t,i)=>!used.has(i)&&!(jokerTile(t,st)&&useJ-->0));let sum=remaining.reduce((z,t)=>z+(jokerTile(t,st)?0:(logical(t,st)?.n||0)),0);let pairIds=[...used].map(i=>tiles[i]?.id).filter(Boolean);let jokerTiles=tiles.filter(t=>jokerTile(t,st)).slice(0,Math.max(0,5-pairs));if(count>=5){let singles=tiles.filter((t,i)=>!used.has(i)&&!jokerTile(t,st)).slice(0,jokerTiles.length);pairIds.push(...jokerTiles.map(t=>t.id),...singles.map(t=>t.id))}return{count,penalty:count>=5?sum*2:null,pairIds}}
function App(){
 const[name,setName]=useState(savedProfile.name||"Oyuncu"),[avatar,setAvatar]=useState(savedProfile.avatar||"🦁"),[photo,setPhoto]=useState(savedProfile.photo||""),[screen,setScreen]=useState("home"),[rooms,setRooms]=useState([]),[room,setRoom]=useState(null),[st,setSt]=useState(null),[hand,setHand]=useState([]),[slots,setSlots]=useState(Array(32).fill(null)),[sel,setSel]=useState([]),[chosenGroups,setChosenGroups]=useState([]),[msg,setMsg]=useState("");
 const[mode,setMode]=useState("katlamasiz"),[help,setHelp]=useState(true),[hands,setHands]=useState(5),[code,setCode]=useState(""),[serverUrl,setServerUrl]=useState(API);
 useEffect(()=>{s.on("lobby",setRooms);s.on("state",setSt);s.on("hand",h=>{setHand(h);setSlots(old=>{let ids=new Set(h.map(t=>t.id)),kept=old.map(t=>t&&ids.has(t.id)?h.find(x=>x.id===t.id):null),present=new Set(kept.filter(Boolean).map(t=>t.id)),add=h.filter(t=>!present.has(t.id));for(let t of add){let k=kept.indexOf(null);if(k<0)kept.push(t);else kept[k]=t}return kept})});s.on("joined",x=>{setRoom(x);setScreen("room")});s.on("err",setMsg);return()=>{s.off("lobby");s.off("state");s.off("hand");s.off("joined");s.off("err")}},[]);
 const saveProfile=()=>{let p={name:name.trim()||"Oyuncu",avatar,photo};localStorage.setItem("okeyProfile",JSON.stringify(p));setName(p.name);s.emit("profileUpdate",p);setMsg("Profil kaydedildi.");setScreen("home")};
 const choosePhoto=e=>{let f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith("image/"))return setMsg("Lütfen bir fotoğraf seç.");let rd=new FileReader();rd.onload=()=>{let im=new Image();im.onload=()=>{let c=document.createElement("canvas"),size=256;c.width=size;c.height=size;let m=Math.min(im.width,im.height),sx=(im.width-m)/2,sy=(im.height-m)/2;c.getContext("2d").drawImage(im,sx,sy,m,m,0,0,size,size);let data=c.toDataURL("image/jpeg",.78);setPhoto(data);setAvatar("")};im.src=rd.result};rd.readAsDataURL(f)};
 const saveServer=()=>{localStorage.setItem("okeyServer",serverUrl.trim());setMsg("Sunucu adresi kaydedildi. Değişikliğin aktif olması için uygulamayı yeniden aç.")};
 const create=()=>{let c=(Math.floor(100000+Math.random()*900000)).toString();s.emit("join",{code:c,name,avatar,photo,create:true,settings:{mode,help,hands:+hands}})};
 const join=c=>s.emit("join",{code:c,name,avatar,photo,create:false});
 const isOkey=t=>!!(st?.okey&&t?.c===st.okey.c&&t?.n===st.okey.n);
 const toggle=id=>setSel(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]);
 const move=(from,to)=>setSlots(old=>{let a=[...old],x=a[from];if(!x)return a;let y=a[to];a[to]=x;a[from]=y||null;s.emit("reorder",a.filter(Boolean).map(t=>t.id));return a});
 const autoSeries=()=>setHand(a=>{let x=[...a].sort((u,v)=>(u.c||"").localeCompare(v.c||"")||u.n-v.n);s.emit("reorder",x.map(t=>t.id));return x});
 const autoPairs=()=>setHand(a=>{let q={};a.forEach(t=>q[t.c+"-"+t.n]=(q[t.c+"-"+t.n]||0)+1);let x=[...a].sort((u,v)=>(q[v.c+v.n]-q[u.c+u.n])||u.n-v.n);s.emit("reorder",x.map(t=>t.id));return x});
 const groups=rackGroups(slots,st),perTotal=perValue(groups,st),pairInfo=pairAnalysis(slots,st);
 const openFromRack=()=>{let use=chosenGroups.length?groups.filter((_,i)=>chosenGroups.includes(i)):groups;let gs=use.map(g=>g.map(t=>t.id));if(!gs.length)return setMsg("Geçerli per bulunamadı.");s.emit("openGroups",gs);setChosenGroups([])};
 const openPairsRack=()=>{if(pairInfo.count<5)return setMsg("Henüz 5 çift yok.");s.emit("pairs",pairInfo.pairIds)};
 if(screen==="home")return <main className="home"><div className="topbar"><span>👑 VIP</span><span>✉ Mesajlar</span><span>👥 Arkadaşlar</span><span>⚙ Ayarlar</span></div><div className="hero"><div className="logo"><span>1</span><span>0</span><span>1</span></div><h1>OKEY ARENA</h1><p className="tag">İstanbul gecelerinde masanı kur</p><div className="homeProfile"><div className="profileAvatar">{photo?<img src={photo}/>:<span>{avatar||"🦁"}</span>}</div><div><b>{name}</b><button onClick={()=>setScreen("profile")}>Profili Düzenle</button></div></div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Kullanıcı adın"/><div className="homeBtns"><button onClick={()=>setScreen("create")}>🀄 ODA AÇ<br/><small>Kendi masanı kur</small></button><button onClick={()=>setScreen("find")}>👥 ODA BUL<br/><small>Açık masalara katıl</small></button></div><p>{msg}</p><div className="homeDock"><button onClick={()=>setScreen("profile")}>👤 Profil</button><span>🏆 Sıralama</span><span>📻 Radyo</span><span>⭐ Etkinlikler</span></div></div></main>;
 if(screen==="profile")return <main className="panelPage"><section className="panel profilePanel"><button className="back" onClick={()=>setScreen("home")}>←</button><h2>PROFİLİM</h2><div className="bigAvatar">{photo?<img src={photo}/>:<span>{avatar||"🦁"}</span>}</div><label>Kullanıcı adı</label><input maxLength={18} value={name} onChange={e=>setName(e.target.value)} placeholder="Kullanıcı adın"/><label>Hazır avatarlar</label><div className="avatarGrid">{AVATARS.map(a=><button className={!photo&&avatar===a?"chosen":""} onClick={()=>{setAvatar(a);setPhoto("")}}>{a}</button>)}</div><label className="galleryButton">📷 GALERİDEN FOTOĞRAF SEÇ<input type="file" accept="image/*" onChange={choosePhoto}/></label>{photo&&<button className="removePhoto" onClick={()=>{setPhoto("");setAvatar("🦁")}}>Fotoğrafı kaldır</button>}<button className="gold" onClick={saveProfile}>PROFİLİ KAYDET</button><hr/><label>Android test sunucusu</label><div className="serverRow"><input value={serverUrl} onChange={e=>setServerUrl(e.target.value)} placeholder="http://192.168.1.10:3001"/><button onClick={saveServer}>Kaydet</button></div><small>Telefonda test ederken bilgisayarının yerel IP adresini yazabilirsin. Play Store sürümünde internet sunucusu kullanılacak.</small><p>{msg}</p></section></main>;
 if(screen==="create")return <main className="panelPage"><section className="panel"><button className="back" onClick={()=>setScreen("home")}>←</button><h2>ODA AÇ</h2><label>Oyun modu</label><div className="choice"><button className={mode==="katlamasiz"?"on":""} onClick={()=>setMode("katlamasiz")}>Katlamasız</button><button className={mode==="katlamali"?"on":""} onClick={()=>setMode("katlamali")}>Katlamalı</button></div><label>Yardım</label><div className="choice"><button className={help?"on":""} onClick={()=>setHelp(true)}>Yardımlı</button><button className={!help?"on":""} onClick={()=>setHelp(false)}>Yardımsız</button></div><label>El sayısı</label><select value={hands} onChange={e=>setHands(e.target.value)}>{[1,3,5,7,10,15,20].map(x=><option key={x} value={x}>{x} El</option>)}</select><button className="gold" onClick={create}>ODAYI OLUŞTUR</button></section></main>;
 if(screen==="find")return <main className="panelPage"><section className="panel wide"><button className="back" onClick={()=>setScreen("home")}>←</button><h2>ODA BUL</h2><div className="roomList">{rooms.length?rooms.map(r=><div className="roomCard"><div><b>Oda #{r.code}</b><small>{r.count}/4 oyuncu • {r.mode==="katlamali"?"Katlamalı":"Katlamasız"} • {r.help?"Yardımlı":"Yardımsız"} • {r.hands} El</small></div><button onClick={()=>join(r.code)}>KATIL</button></div>):<p>Açık oda bulunamadı.</p>}</div><div className="codeJoin"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Oda kodu"/><button onClick={()=>join(code)}>KODLA KATIL</button></div><p>{msg}</p></section></main>;
 return <main className="game premiumGame"><header><b>101 OKEY</b><span>ODA #{room?.code}</span><span>{room?.settings?.mode==="katlamali"?"KATLAMALI":"KATLAMASIZ"}</span><span>{room?.settings?.help?"YARDIMLI":"YARDIMSIZ"}</span><span>{room?.settings?.hands} EL</span></header>
 <div className="players">{st?.players?.map((p,i)=><div className={st.current===i?"turn":""}><div className="playerAvatar">{p.photo?<img src={p.photo}/>:<span>{p.avatar||"🦁"}</span>}</div><div><b>{p.name}</b><small>{p.score} ceza {p.opened?"• AÇTI":""}</small></div></div>)}</div>
 <section className="table"><div className="istanbulGlow"></div><div className="indicator"><label>GÖSTERGE</label>{st?.indicator&&<Tile t={st.indicator}/>}</div><div className="okey"><label>OKEY</label>{st?.okey&&<Tile t={st.okey}/>}</div><div className="melds">{st?.melds?.map((m,i)=><div key={i}><small>{m.name}</small>{m.ts?.map(t=><Tile t={t}/>)}</div>)}</div><div className="discard"><label>YER</label>{st?.discard?.length?<Tile t={st.discard.at(-1)}/>:<b>—</b>}</div></section>
 <div className="message">{msg}</div><div className="actions">{!st?.started?<button onClick={()=>s.emit("start")}>OYUNU BAŞLAT</button>:<><button onClick={()=>s.emit("draw")}>ORTADAN ÇEK</button><button onClick={()=>s.emit("take")}>YANDAN AL</button><button onClick={openFromRack}>PERLERİ AÇ</button><button onClick={openPairsRack}>ÇİFT AÇ</button><button onClick={()=>{if(sel.length===1){s.emit("discard",sel[0]);setSel([])}}}>TAŞ AT</button></>}</div>
 <div className="groupBar"><span>PERLER:</span>{groups.map((g,i)=><button className={chosenGroups.includes(i)?"picked":""} onClick={()=>setChosenGroups(a=>a.includes(i)?a.filter(x=>x!==i):[...a,i])}>Per {i+1} • {perValue([g],st)}</button>)}<small>Bir pere bir kez bas → grubun tamamı seçilir. Hiç seçmezsen tüm geçerli perler açılır.</small></div>
 <div className="privateCounters"><div><small>SADECE SEN GÖRÜRSÜN</small><b>PER <strong>{perTotal}</strong></b></div><div><small>{pairInfo.count} ÇİFT</small><b>ÇİFT <strong>{pairInfo.penalty===null?"—":pairInfo.penalty}</strong></b></div></div>
 <div className="optional"><span>Otomatik dizmek istemezsen kullanma:</span><button onClick={autoSeries}>Seri Diz</button><button onClick={autoPairs}>Çift Diz</button><strong>Boş hücreler perleri ayırır.</strong></div>
 <section className="rack slotRack">{[0,1].map(row=><div className="rackrow" key={row}>{slots.slice(row*16,row*16+16).map((t,j)=>{let i=row*16+j;return <div className="slot" key={i} onDragOver={e=>e.preventDefault()} onDrop={e=>move(+e.dataTransfer.getData("from"),i)}>{t?<Tile t={t} sel={sel.includes(t.id)} onClick={()=>toggle(t.id)} drag={e=>e.dataTransfer.setData("from",String(i))} isOkey={isOkey(t)} allowReveal={true}/>:<span className="emptySlot">+</span>}</div>})}</div>)}</section><div className="okeyHint">💡 Okey elindeyse diğer taşlardan farklı görünmez. Okey taşına 5 saniye basılı tutarak kontrol edebilirsin.</div>
 </main>
}createRoot(document.getElementById("root")).render(<App/>);