const http=require("http"),express=require("express"),cors=require("cors"),path=require("path");const{Server}=require("socket.io");const a=express();a.use(cors());
a.get("/health",(req,res)=>res.status(200).json({ok:true,service:"101-okey-arena"}));
const webDir=path.join(__dirname,"../client/dist");
a.use(express.static(webDir));const sv=http.createServer(a),io=new Server(sv,{cors:{origin:"*"}}),R=new Map(),cs=["Siyah","Kırmızı","Mavi","Sarı"];function deck(){let d=[];for(let c of cs)for(let n=1;n<=13;n++)for(let k=0;k<2;k++)d.push({c,n,id:c+n+k+Math.random()});for(let k=0;k<2;k++)d.push({c:"Sahte",n:0,id:"s"+k+Math.random()});return d.sort(()=>Math.random()-.5)}const nx=n=>n==13?1:n+1;function joker(t,g){return t.c==g.c&&t.n==nx(g.n)}function nt(t,g){return t.c=="Sahte"?{c:g.c,n:nx(g.n)}:t}function setok(ts,g){if(ts.length<3)return false;let j=ts.filter(t=>joker(t,g)).length,x=ts.filter(t=>!joker(t,g)).map(t=>nt(t,g));if(!x.length)return true;if(x.every(t=>t.n==x[0].n)&&new Set(x.map(t=>t.c)).size==x.length&&x.length+j<=4)return true;if(!x.every(t=>t.c==x[0].c))return false;let ns=x.map(t=>t.n).sort((a,b)=>a-b);if(new Set(ns).size!=ns.length)return false;let gap=0;for(let i=1;i<ns.length;i++)gap+=ns[i]-ns[i-1]-1;return gap<=j}function pairs(ts,g){let used=new Set(),p=0,j=ts.filter(t=>joker(t,g)).length;for(let i=0;i<ts.length;i++)for(let k=i+1;k<ts.length;k++){if(used.has(i)||used.has(k)||joker(ts[i],g)||joker(ts[k],g))continue;let a=nt(ts[i],g),b=nt(ts[k],g);if(a.c==b.c&&a.n==b.n){used.add(i);used.add(k);p++}}return p+j}function pub(r){return{started:r.started,current:r.g?.cur??null,opening:r.g?.open??101,indicator:r.g?.ind,okey:r.g?{c:r.g.ind.c,n:nx(r.g.ind.n)}:null,discard:r.g?.disc||[],melds:r.g?.melds||[],players:r.ps.map(p=>({id:p.id,name:p.name,avatar:p.avatar||"🦁",photo:p.photo||"",score:p.score,opened:p.opened}))}}function send(r){io.to(r.code).emit("state",pub(r))}function lobby(){return [...R.values()].filter(r=>!r.started&&r.ps.length<4).map(r=>({code:r.code,count:r.ps.length,mode:r.settings?.mode||"katlamasiz",help:r.settings?.help!==false,hands:+(r.settings?.hands||5)}))}
function broadcastLobby(){io.emit("lobby",lobby())}
io.on("connection",s=>{s.emit("lobby",lobby());s.on("join",({code,name,avatar,photo,settings,create})=>{let r=R.get(code);if(!r){if(!create)return s.emit("err","Oda bulunamadı.");r={code,owner:s.id,settings:{mode:"katlamasiz",help:true,hands:5,...settings},ps:[],started:false};R.set(code,r)}if(r.started||r.ps.length>=4)return s.emit("err","Oda dolu.");r.ps.push({id:s.id,name:(name||"Oyuncu").slice(0,18),avatar:avatar||"🦁",photo:(photo||"").slice(0,180000),score:0,hand:[],opened:false});s.join(code);s.data.c=code;s.emit("joined",{code,settings:r.settings,owner:r.owner===s.id});send(r);broadcastLobby()});s.on("reorder",ids=>{let r=R.get(s.data.c),p=r?.ps.find(p=>p.id==s.id);if(!p||!Array.isArray(ids))return;let m=new Map(p.hand.map(t=>[t.id,t]));let nh=ids.map(id=>m.get(id)).filter(Boolean);for(let t of p.hand)if(!ids.includes(t.id))nh.push(t);p.hand=nh;io.to(p.id).emit("hand",p.hand)});

s.on("profileUpdate",p=>{let r=R.get(s.data.c),u=r?.ps.find(x=>x.id==s.id);if(!u||!p)return;u.name=(p.name||u.name).slice(0,18);u.avatar=p.avatar||"🦁";u.photo=(p.photo||"").slice(0,180000);send(r)});s.on("start",()=>{let r=R.get(s.data.c);if(!r||r.owner!=s.id||r.ps.length!=4)return s.emit("err","4 oyuncu gerekli.");let d=deck(),ind=d.pop();while(ind.c=="Sahte"){d.unshift(ind);ind=d.pop()}r.g={d,ind,cur:0,open:101,disc:[],melds:[]};r.ps.forEach((p,i)=>{p.hand=[];p.opened=false;for(let k=0;k<(i?21:22);k++)p.hand.push(d.pop());io.to(p.id).emit("hand",p.hand)});r.started=true;send(r);broadcastLobby()});s.on("draw",()=>{let r=R.get(s.data.c),i=r?.ps.findIndex(p=>p.id==s.id);if(!r?.started||i!=r.g.cur)return;let p=r.ps[i];if(p.hand.length<=21)p.hand.push(r.g.d.pop());io.to(p.id).emit("hand",p.hand);send(r)});s.on("take",()=>{let r=R.get(s.data.c),i=r?.ps.findIndex(p=>p.id==s.id);if(!r?.started||i!=r.g.cur||!r.g.disc.length)return;let p=r.ps[i],t=r.g.disc.pop();p.hand.push(t);p.side=t;p.sideFrom=r.g.lastDiscardBy;io.to(p.id).emit("hand",p.hand);send(r)});s.on("openGroups",groups=>{let r=R.get(s.data.c),p=r?.ps.find(p=>p.id==s.id);if(!r?.started||!p||p.opened||!Array.isArray(groups))return;
 let flat=groups.flat(),uniq=[...new Set(flat)];if(flat.length!==uniq.length)return s.emit("err","Aynı taş iki grupta kullanılamaz.");
 let real=groups.map(g=>g.map(id=>p.hand.find(t=>t.id==id)).filter(Boolean)).filter(g=>g.length);
 if(!real.length||real.some(g=>!setok(g,r.g.ind)))return s.emit("err","Istakadaki perlerden biri geçersiz.");
 let ids=new Set(uniq),ts=p.hand.filter(t=>ids.has(t.id));if(ts.length!==uniq.length)return s.emit("err","Taş seçimi geçersiz.");
 let total=ts.reduce((z,t)=>z+(joker(t,r.g.ind)?0:nt(t,r.g.ind).n),0),need=r.settings?.mode=="katlamali"?r.g.open:101;
 if(total<need)return s.emit("err","Per toplamı "+total+". Açmak için "+need+" gerekli.");
 p.hand=p.hand.filter(t=>!ids.has(t.id));p.opened=true;real.forEach(g=>r.g.melds.push({name:p.name,ts:g}));
 if(r.settings?.mode=="katlamali")r.g.open=total+1;if(p.side&&ids.has(p.side.id)){let q=r.ps.find(x=>x.id===p.sideFrom);if(q)q.score+=p.side.n*10;}p.side=null;p.sideFrom=null;
 io.to(p.id).emit("hand",p.hand);send(r)});
s.on("open",ids=>{let r=R.get(s.data.c),p=r?.ps.find(p=>p.id==s.id);if(!p||p.opened)return;let ts=p.hand.filter(t=>ids.includes(t.id));if(!setok(ts,r.g.ind))return s.emit("err","Seçilen taşlar geçerli seri/per değil.");let total=ts.reduce((z,t)=>z+(joker(t,r.g.ind)?0:nt(t,r.g.ind).n),0),need=r.settings?.mode=="katlamali"?r.g.open:101;if(total<need)return s.emit("err","Açılış toplamı "+total+", gerekli "+need);p.hand=p.hand.filter(t=>!ids.includes(t.id));p.opened=true;r.g.melds.push({name:p.name,ts});if(r.settings?.mode=="katlamali")r.g.open=total+1;if(p.side&&ids.includes(p.side.id)){let q=r.ps.find(x=>x.id===p.sideFrom);if(q)q.score+=p.side.n*10;}p.side=null;p.sideFrom=null;io.to(p.id).emit("hand",p.hand);send(r)});s.on("pairs",ids=>{let r=R.get(s.data.c),p=r?.ps.find(p=>p.id==s.id);if(!r?.started||!p||p.opened)return;
 let chosen=p.hand.filter(t=>ids.includes(t.id));let used=new Set(),pairIds=[],jokers=[];
 chosen.forEach(t=>{if(joker(t,r.g.ind))jokers.push(t)});
 for(let i=0;i<chosen.length;i++)for(let j=i+1;j<chosen.length;j++){let a=chosen[i],b=chosen[j];if(used.has(a.id)||used.has(b.id)||joker(a,r.g.ind)||joker(b,r.g.ind))continue;let x=nt(a,r.g.ind),y=nt(b,r.g.ind);if(x.c==y.c&&x.n==y.n){used.add(a.id);used.add(b.id);pairIds.push(a.id,b.id)}}
 let pairCount=pairIds.length/2;while(pairCount<5&&jokers.length){let single=chosen.find(t=>!used.has(t.id)&&!joker(t,r.g.ind));if(!single)break;let j=jokers.shift();used.add(single.id);used.add(j.id);pairIds.push(single.id,j.id);pairCount++}
 if(pairCount<5)return s.emit("err","Çift açmak için en az 5 geçerli çift gerekli.");
 let openIds=new Set(pairIds),ts=p.hand.filter(t=>openIds.has(t.id));p.hand=p.hand.filter(t=>!openIds.has(t.id));p.opened=true;
 r.g.melds.push({name:p.name,ts,type:"çift"});
 if(p.side){if(!openIds.has(p.side.id)){p.hand.push(...ts);p.opened=false;r.g.melds.pop();return s.emit("err","Yandan aldığın taşı açılışında kullanmak zorundasın.");}let q=r.ps.find(x=>x.id===p.sideFrom);if(q)q.score+=p.side.n*20;p.side=null;p.sideFrom=null}
 io.to(p.id).emit("hand",p.hand);send(r)});s.on("discard",id=>{let r=R.get(s.data.c),i=r?.ps.findIndex(p=>p.id==s.id);if(!r?.started||i!=r.g.cur)return;let p=r.ps[i];if(p.side)return s.emit("err","Yandan taş aldın. Bu taşı kullanarak açmadan taş atamazsın.");let x=p.hand.findIndex(t=>t.id==id);if(x<0)return;let t=p.hand.splice(x,1)[0];r.g.disc.push(t);r.g.lastDiscardBy=p.id;if(!p.hand.length){let none=r.ps.filter(q=>q!=p).every(q=>!q.opened),ok=joker(t,r.g.ind);r.ps.forEach(q=>q.score+=q==p?(none?(ok?-400:-200):0):(none?(ok?800:400):200));r.started=false;s.emit("err","El bitti.");send(r);return}p.side=null;r.g.cur=(i+1)%4;io.to(p.id).emit("hand",p.hand);send(r)})});a.get("*",(req,res)=>{if(req.path.startsWith("/socket.io"))return;res.sendFile(path.join(webDir,"index.html"))});
const PORT=process.env.PORT||3001;
sv.listen(PORT,"0.0.0.0",()=>console.log("101 Okey Arena hazır:",PORT));
